### ISSUE TITLE
Loosen engine/npm versions

### ISSUE THREAD

**Issue by agjohnson** [readthedocs/readthedocs-client#15]
I don't have access to this repo, but the change here is small anyways.

The package.json expected engine/npm versions are exact matches right now, and should be loosened to `^18.x.x` and `^9.x.x`. This matches versions to the minor version, which is sufficient as Node follows semver. This change will avoid everyone maintaining multiple minor/bugfix versions of Node 18 to satisfy strict versions.

**Comment by humitos** [comment]
> I don't have access to this repo, but the change here is small anyways.

I transfered it to `readthedocs` organization now.
