### ISSUE TITLE
Max height for expanded flyout menu overflows viewport a bit

### ISSUE THREAD

**Issue by benjaoming** [readthedocs/readthedocs-client#16]
Not sure if this is a good place to post this?

The scaling works fine, except it's like the height of the menu itself is missing from the calculation?

Edit: Btw this is Firefox.

![image](https://user-images.githubusercontent.com/374612/226730342-3f4539d8-5c4e-4673-8a4b-7f852a228231.png)

Things are working great btw!! :clap:

**Comment by humitos** [comment]
This is an issue in the old flyout. There is no flyout implemented in the new addons. I'm closing this for now.
