### ISSUE TITLE
Development: create more examples in `public/`

### ISSUE THREAD

**Issue by humitos** [readthedocs/readthedocs-client#27]
We already have some examples for Sphinx and Pelican. I'd like to create more for:

- [x] sphinx with furo (http://test-builds.devthedocs.org/en/furo/)
- [x] mkdocs (http://test-builds.devthedocs.org/en/mkdocs/)
- [x] material for mkdocs (http://test-builds.devthedocs.org/en/mkdocs-material/)
- [x] docusaurus (http://test-builds.devthedocs.org/en/docusaurus/)
- [ ] docsify
- [x] jupyter book (http://test-builds.devthedocs.org/en/jupyter-book/)
- [ ] non-standard doctool (see https://pycamp.es)

These are useful to check styles and understand how each feature looks on these different doctools/themes. They have been being useful to find required overrides in CSS to avoid them looking terrible 😄

**Comment by humitos** [comment]
The way to work with them is:

1. execute `npm run dev` in this repository
2. spin up the RTD development instance: `inv docker.up`
3. build the desired branches for `test-builds`
4. open the documentation for that particular version
5. modify as you like the javascript client and refresh the page to see the changes

**Comment by humitos** [comment]
We could get more creative here and make everything to live in this repository. However, that requires more time and maintenance over time. I prefer to keep the examples just in one place for now. This approach works for development for now.

Another "simple approach" could be to `wget` those versions from the already built `test-builds` project. Kind of a hack, but at least we are not duplicating content -- or even `git clone` that repo and build multiples branches.

This solution won't work locally tho, but for quick tests in Read the Docs may be enough.

**Comment by humitos** [comment]
I created some initial docs in #35 that generates a pretty basic index that points to the examples we currently have in this repository.

**Comment by agjohnson** [comment]
I also added a generic version of this in `/public/index.html` to show all the implementations and elements in one place. I found it helpful for some testing purposes.

It sounds like we can close this out however, as we don't necessarily want to configure all of these tools as development test cases, and we have test-build test cases we can use for QA.
